---
name: stock

services:
  stock:
    image: mayanghua/instock:202503
    restart: unless-stopped
    ports:
      - 9988:9988
    environment:
      - db_host=mysql
      - db_port=3306
      - db_user=root
      - db_password=mysqlpassword
      - db_database=instockdb
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/mysql

networks:
  default:
    external: true
    name: compose
