---
name: stock

services:
  stock:
    image: atompi/stock:latest
    restart: unless-stopped
    ports:
      - 9988:9988
    environment:
      - db_host=mysql
      - db_port=3306
      - db_user=root
      - db_password=mysqlpassword
      - db_database=instockdb
    volumes:
      - stock_log:/data/InStock/instock/log
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --mysql-native-password=ON
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/mysql
  stock_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/stock/log

networks:
  default:
    external: true
    name: compose
