---
name: stock

services:
  stock:
    image: atompi/stock:latest
    restart: unless-stopped
    ports:
      - 9988:9988
    environment:
      - db_host=mariadb
      - db_port=3306
      - db_user=root
      - db_password=mariadbpassword
      - db_database=instockdb
    volumes:
      - stock_log:/data/InStock/instock/log
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11.4.5
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/mariadb
  stock_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/stock/log

networks:
  default:
    external: true
    name: compose
