---
name: kafka

services:
  kafka-0:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092"
    env_file:
      - base.env
      - 0.env
    volumes:
      - kafka_0_data:/bitnami/kafka
  kafka-1:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092"
    env_file:
      - base.env
      - 1.env
    volumes:
      - kafka_1_data:/bitnami/kafka
  kafka-2:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092"
    env_file:
      - base.env
      - 2.env
    volumes:
      - kafka_2_data:/bitnami/kafka
  schema-registry:
    image: docker.io/bitnami/schema-registry:7.9
    restart: unless-stopped
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.2.0
    restart: unless-stopped
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8080:8080"

volumes:
  kafka_0_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/kafka-0
  kafka_1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/kafka-1
  kafka_2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/kafka-2

networks:
  default:
    external: true
    name: compose
