---
name: redis

services:
  server:
    image: redis:7
    restart: unless-stopped
    command:
      - --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data

networks:
  default:
    external: true
    name: compose
